# Javascript Node CircleCI 2.0 configuration file
version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.8

    environment:
    - NODE_ENV: development

    steps:
    - checkout

    - restore_cache:
        keys:
        - root-dependencies-{{ checksum "yarn.lock" }}

    - run: yarn --frozen-lockfile

    - save_cache:
        paths:
        - node_modules
        key: root-dependencies-{{ checksum "yarn.lock" }}

    - run: yarn test
